#!/usr/bin/env node
// Scans public/images/ and writes src/data/catalog.ts.
import { readdirSync, writeFileSync, mkdirSync } from "fs"
import { join } from "path"

const imgDir  = join(process.cwd(), "public", "images")
const outDir  = join(process.cwd(), "src", "data")
const outFile = join(outDir, "catalog.ts")

mkdirSync(outDir, { recursive: true })

let files = []
try {
  files = readdirSync(imgDir)
} catch {
  console.warn("  WARN public/images not found — catalog will be empty.")
}

const IMAGE_RE = /\.(jpe?g|webp|gif|avif)$/i  // .png excluded (logo only)
const VIDEO_RE = /\.(mp4|webm|mov|m4v)$/i
const isProductImage = (f) => IMAGE_RE.test(f)

const numericSort = (a, b) => {
  const na = parseInt(a, 10)
  const nb = parseInt(b, 10)
  return (isNaN(na) || isNaN(nb)) ? a.localeCompare(b) : na - nb
}

const images = files.filter(isProductImage).sort(numericSort)
const videos = files.filter((f) => VIDEO_RE.test(f)).sort()

const encode = (name) => encodeURIComponent(name)

const lines = [
  "// Auto-generated by scripts/generate-catalog.mjs — do not edit manually.",
  "",
  "export const CATALOG_IMAGES: string[] = [",
  ...images.map((f) => '  "/images/' + encode(f) + '",'),
  "]",
  "",
  "export const CATALOG_VIDEOS: string[] = [",
  ...videos.map((f) => '  "/images/' + encode(f) + '",'),
  "]",
  "",
]

writeFileSync(outFile, lines.join("\n"), "utf-8")
console.log("  Catalog: " + images.length + " images, " + videos.length + " videos -> src/data/catalog.ts")
